# Generated by Django 4.1.2 on 2022-10-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_mynetwork_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mynetwork',
            old_name='following',
            new_name='follow',
        ),
        migrations.RenameField(
            model_name='mynetwork',
            old_name='followers',
            new_name='myfollowers',
        ),
    ]
