# Generated by Django 4.1.2 on 2022-10-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='slug',
        ),
    ]
