# Generated by Django 4.1.2 on 2022-10-21 15:45

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('articles', '0003_remove_comments_profile_alter_comments_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='tagline',
        ),
        migrations.AddField(
            model_name='articles',
            name='tagline',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
