# Generated by Django 4.1.2 on 2022-10-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_articles_tagline_articles_tagline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='tagline',
            new_name='tags',
        ),
    ]
