# Generated by Django 4.1.2 on 2022-10-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_tagline_articles_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
