# Generated by Django 4.1.2 on 2022-10-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_prompts_posts_prompts_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompts',
            name='posts',
        ),
        migrations.AddField(
            model_name='writeups',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
