# Generated by Django 4.1.2 on 2022-10-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_prompts_posts_writeups_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeups',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
