# Generated by Django 4.1.2 on 2022-10-27 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_following_mynetwork_follow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0011_alter_writeups_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writeups_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='writeupprofile', to='accounts.profile')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='writeupsLikes', to=settings.AUTH_USER_MODEL)),
                ('writeups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeupsComments', to='articles.writeups')),
            ],
        ),
    ]
