# Generated by Django 4.1.2 on 2022-10-31 12:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_writeups_comments_likes_writeups_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeups',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writeups',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
