# Generated by Django 4.1.2 on 2022-10-31 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_writeups_date_alter_articles_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
